-- Create webhook_channels table for storing Google Calendar push notification channels
-- REQ-2-028: Webhook Channel Table Migration

CREATE TABLE webhook_channels (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  calendar_source_id UUID NOT NULL REFERENCES calendar_sources(id) ON DELETE CASCADE,
  channel_id TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  expiration TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (channel_id)
);

-- Index for finding channels by calendar_source
CREATE INDEX idx_webhook_channels_calendar_source ON webhook_channels(calendar_source_id);

-- Index for finding channels that need renewal (expiring soon)
CREATE INDEX idx_webhook_channels_expiration ON webhook_channels(expiration);

COMMENT ON TABLE webhook_channels IS 'Google Calendar push notification channels for real-time updates';
COMMENT ON COLUMN webhook_channels.channel_id IS 'Unique channel ID generated by our application';
COMMENT ON COLUMN webhook_channels.resource_id IS 'Resource ID returned by Google when creating the watch';
COMMENT ON COLUMN webhook_channels.expiration IS 'When this channel expires and needs renewal';
